### ISSUE TITLE
add support for todo.txt format

### ISSUE THREAD

**Issue by cizmazia** [FossifyOrg/Notes#37]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Add a setting to use the [todo.txt](https://github.com/todotxt/todo.txt) fromat instead of JSON for saving/exporting task lists.

### Why do you want this feature?

It would enable to use a plain text editor to modify the task lists. Task list files can be synchronized to other devices using [Syncthing](https://github.com/syncthing/syncthing).

The only existing alternative app [SimpleTask](https://github.com/mpcjanssen/simpletask-android) is not actively developed any longer.
