### ISSUE TITLE
[Feature request] Please add an option to decrease space between checklist items.

### ISSUE THREAD

**Issue by kajoken** [FossifyOrg/Notes#51]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I would like to request the option to manipulate the space between checklist items. I was thinking of something similar to this:

[ ] compact
[ ] normal

### Why do you want this feature?

I just switched my shopping list app to Fossify Notes since my app hasn't been updated in four years and is now crashing allot. The biggest difference between the two is the spacing. On my old shopping list I could see more items at once since the spacing was very small. Fossify Notes spacing on the other hand is way bigger and I need to scroll way more to see all items.

Would be nice if this FR could be considered in any way.

Thank you :)
