### ISSUE TITLE
Search for note, checklist items and text

### ISSUE THREAD

**Issue by zwrmueller** [FossifyOrg/Notes#76]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

A search function could come in handy which narrows the offered notes by typing into the search field.

### Why do you want this feature?

It happens that I have a mess of notes and I miss an option to jump to a note faster than scrolling through a long list of notes. 

### Additional information

Related is a search funktion for text (in text notes) or checkbox items in checklist notes. 

But the search for a specific note is my main concern.

Thanx for pushing this on.

**Comment by deeeseee** [comment]
Agreed 100%. There really needs to be a way to search among all notes & checklists, but also inside a single note/checklist.

**Comment by jcperil** [comment]
I need this feature as well. Scrolling through a big checklist to check a particular item is time consuming. A search would simplify this.

**Comment by AbsoluteMe** [comment]
Yes it is a must have feature, else how can I find in hundert notes, the note I need!?

**Comment by AbsoluteMe** [comment]
> ### Checklist
> * [x]  I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.[x]  I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.[x]  I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.[x]  **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**[x]  This issue contains only one feature request.[x]  I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).[ ]  I optionally [donated](https://fossify.org/donate) to support the Fossify mission.
> 
> ### Feature description
> A search function could come in handy which narrows the offered notes by typing into the search field.
> 
> ### Why do you want this feature?
> It happens that I have a mess of notes and I miss an option to jump to a note faster than scrolling through a long list of notes.
> 
> ### Additional information
> Related is a search funktion for text (in text notes) or checkbox items in checklist notes.
> 
> But the search for a specific note is my main concern.
> 
> Thanx for pushing this on.
 
Can we modify the subject to:
Search/Filter all notes/checklists functionality in Open Note Window
 it maybe more clear

**Comment by naveensingh** [comment]
Yes.

**Comment by kokoko3k** [comment]
I second this!

**Comment by electriquo** [comment]
I've been waiting for this for a looong time! :)

I really don't want to switch to an alternative because I want to support FOSS as much as possible. I'm sure there are plenty of others like me who would be very happy to see this implemented too.

Maybe spin up a coding agent and let it work its magic? (although I no access for such one) :)
